server:
  port: 9003
  servlet:
    session:
      cookie:
        name: ACCESS_SESSION
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      grant-type: authorization_code
      access-token-uri: http://localhost:9000/auth/oauth/token
      user-authorization-uri: http://localhost:9000/auth/oauth/authorize
      pre-established-redirect-uri: http://localhost:9003/authorize/login
    resource:
      user-info-uri: http://localhost:9002/user/me
    sso:
      login-path: /authorize/login
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/model?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
